export interface StockMcp {
  name: string;
  label: string;
  category: string;
  description: string;
  command?: string;
  args?: string[];
  url?: string;
  envKeys: string[];
  authType?: 'none' | 'api_key' | 'oauth';
  oauthProvider?: string;
  keyGetUrl?: string;
  keyGetLabel?: string;
}

export const STOCK_MCPS: StockMcp[] = [
  // ── 1. CODE & GIT ────────────────────────────────────────────────────────
  {
    name: 'github-mcp-server',
    label: 'GitHub',
    category: 'Code & Git',
    description: 'Inspect repositories, issues, pull requests, commits, and automate GitHub operations.',
    command: 'npx',
    args: ['-y', 'github-mcp-server'],
    envKeys: ['GITHUB_TOKEN'],
    authType: 'oauth',
    oauthProvider: 'github',
    keyGetUrl: 'https://github.com/settings/tokens',
    keyGetLabel: 'Or Generate GITHUB_TOKEN manually',
  },
  {
    name: 'gitlab-mcp-server',
    label: 'GitLab',
    category: 'Code & Git',
    description: 'Manage GitLab projects, merge requests, CI pipelines, and repository files.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-gitlab'],
    envKeys: ['GITLAB_PERSONAL_ACCESS_TOKEN'],
    authType: 'oauth',
    oauthProvider: 'gitlab',
    keyGetUrl: 'https://gitlab.com/-/user_settings/personal_access_tokens',
    keyGetLabel: 'Or Generate GitLab Token manually',
  },
  {
    name: 'filesystem-mcp',
    label: 'Local Filesystem',
    category: 'Code & Git',
    description: 'Read, write, search, and list local filesystem directories with controlled boundaries.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-filesystem'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'git-mcp',
    label: 'Git CLI',
    category: 'Code & Git',
    description: 'Direct git operations: log, diff, status, branches, commits, and stashes on local repos.',
    command: 'npx',
    args: ['-y', 'mcp-server-git'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'sentry-mcp',
    label: 'Sentry Crash Reporter',
    category: 'Code & Git',
    description: 'Search Sentry production issues, stack traces, release regressions, and error frequencies.',
    command: 'npx',
    args: ['-y', '@sentry/mcp-server'],
    envKeys: ['SENTRY_AUTH_TOKEN'],
    authType: 'oauth',
    oauthProvider: 'sentry',
    keyGetUrl: 'https://sentry.io/settings/account/api/auth-tokens/',
    keyGetLabel: 'Or Generate Sentry Token manually',
  },

  // ── 2. WEB & SCRAPING ────────────────────────────────────────────────────
  {
    name: 'playwright-mcp',
    label: 'Playwright Browser',
    category: 'Web & Scraping',
    description: 'Autonomous browser navigation, clicking, DOM interaction, screenshots, and E2E verification.',
    command: 'npx',
    args: ['-y', '@playwright/mcp@latest'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'puppeteer-mcp',
    label: 'Puppeteer Headless Web',
    category: 'Web & Scraping',
    description: 'Headless Chrome browser automation, JavaScript-heavy page scraping, and PDF generation.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-puppeteer'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'fetch-mcp',
    label: 'HTTP Fetch & HTML to Markdown',
    category: 'Web & Scraping',
    description: 'Clean HTTP requests converting web pages, JSON APIs, and docs into markdown format for LLMs.',
    command: 'uvx',
    args: ['mcp-server-fetch'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'firecrawl-mcp',
    label: 'Firecrawl Web Crawler',
    category: 'Web & Scraping',
    description: 'Deep web scraping, batch crawling, and AI-ready markdown extraction.',
    command: 'npx',
    args: ['-y', 'firecrawl-mcp'],
    envKeys: ['FIRECRAWL_API_KEY'],
    authType: 'api_key',
    keyGetUrl: 'https://firecrawl.dev',
    keyGetLabel: 'Get FIRECRAWL_API_KEY',
  },
  {
    name: 'tavily-mcp',
    label: 'Tavily Search',
    category: 'Web & Scraping',
    description: 'Fast, AI-native web search engine tailored for LLMs and autonomous research agents.',
    command: 'npx',
    args: ['-y', 'tavily-mcp@latest'],
    envKeys: ['TAVILY_API_KEY'],
    authType: 'api_key',
    keyGetUrl: 'https://app.tavily.com',
    keyGetLabel: 'Get TAVILY_API_KEY',
  },
  {
    name: 'brave-search-mcp',
    label: 'Brave Web Search',
    category: 'Web & Scraping',
    description: 'Independent global web and news search without tracking or sponsored ad pollution.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-brave-search'],
    envKeys: ['BRAVE_API_KEY'],
    authType: 'api_key',
    keyGetUrl: 'https://brave.com/search/api/',
    keyGetLabel: 'Get Brave API Key',
  },
  {
    name: 'exa-mcp',
    label: 'Exa Neural Search',
    category: 'Web & Scraping',
    description: 'Semantic embedding search engine to find company research, technical blogs, and links.',
    command: 'npx',
    args: ['-y', 'exa-mcp-server'],
    envKeys: ['EXA_API_KEY'],
    authType: 'api_key',
    keyGetUrl: 'https://exa.ai',
    keyGetLabel: 'Get EXA_API_KEY',
  },
  {
    name: 'curl-mcp',
    label: 'Curl Network Inspector',
    category: 'Web & Scraping',
    description: 'Send custom raw HTTP/HTTPS headers, TLS handshakes, and debug REST APIs.',
    command: 'npx',
    args: ['-y', 'curl-mcp'],
    envKeys: [],
    authType: 'none',
  },

  // ── 3. DATABASES & STORAGE ───────────────────────────────────────────────
  {
    name: 'postgres-mcp-server',
    label: 'PostgreSQL Database',
    category: 'Databases & Storage',
    description: 'Run SQL queries, inspect tables, examine query execution plans, and manage Postgres databases.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-postgres'],
    envKeys: ['POSTGRES_URL'],
    authType: 'api_key',
    keyGetLabel: 'Enter Postgres Connection URL',
  },
  {
    name: 'sqlite',
    label: 'SQLite Database',
    category: 'Databases & Storage',
    description: 'Query and manage local SQLite databases with SQL queries and schema introspection.',
    command: 'uvx',
    args: ['mcp-server-sqlite'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'mysql-mcp-server',
    label: 'MySQL Database',
    category: 'Databases & Storage',
    description: 'Connect, inspect tables, and execute SQL statements on MySQL & MariaDB servers.',
    command: 'npx',
    args: ['-y', 'mysql-mcp-server'],
    envKeys: ['MYSQL_URL'],
    authType: 'api_key',
    keyGetLabel: 'Enter MySQL Connection URL',
  },
  {
    name: 'redis-mcp-server',
    label: 'Redis Cache & Store',
    category: 'Databases & Storage',
    description: 'Inspect keys, TTLs, hash maps, queues, and pub/sub streams on Redis clusters.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-redis'],
    envKeys: ['REDIS_URL'],
    authType: 'api_key',
    keyGetLabel: 'Enter Redis URL',
  },
  {
    name: 'mongodb-mcp-server',
    label: 'MongoDB Atlas',
    category: 'Databases & Storage',
    description: 'Query NoSQL document collections, aggregation pipelines, and JSON schemas.',
    command: 'npx',
    args: ['-y', 'mongodb-mcp-server'],
    envKeys: ['MONGODB_URI'],
    authType: 'api_key',
    keyGetLabel: 'Enter MongoDB URI',
  },
  {
    name: 'snowflake-mcp-server',
    label: 'Snowflake Data Warehouse',
    category: 'Databases & Storage',
    description: 'Execute analytical queries, warehouse compute tracking, and large datasets in Snowflake.',
    command: 'npx',
    args: ['-y', 'snowflake-mcp-server'],
    envKeys: ['SNOWFLAKE_ACCOUNT', 'SNOWFLAKE_USER', 'SNOWFLAKE_PASSWORD'],
    authType: 'api_key',
    keyGetLabel: 'Configure Snowflake Credentials',
  },

  // ── 4. DEVOPS & CLOUD ────────────────────────────────────────────────────
  {
    name: 'docker-mcp',
    label: 'Docker Daemon',
    category: 'DevOps & Cloud',
    description: 'Inspect running containers, stream container logs, check port mappings, and manage images.',
    command: 'npx',
    args: ['-y', 'docker-mcp'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'kubernetes-mcp',
    label: 'Kubernetes Cluster',
    category: 'DevOps & Cloud',
    description: 'Query pods, deployments, services, events, and ingress routing via kubeconfig or K8s API.',
    command: 'npx',
    args: ['-y', 'kubernetes-mcp-server'],
    envKeys: ['KUBECONFIG_BASE64'],
    authType: 'none',
  },
  {
    name: 'aws-mcp-server',
    label: 'AWS Cloud Services',
    category: 'DevOps & Cloud',
    description: 'Query CloudWatch logs, list S3 buckets/objects, inspect EC2 instances, and invoke Lambdas.',
    command: 'npx',
    args: ['-y', 'aws-mcp-server'],
    envKeys: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_REGION'],
    authType: 'api_key',
    keyGetUrl: 'https://console.aws.amazon.com/iam/',
    keyGetLabel: 'Get AWS Access Keys',
  },
  {
    name: 'cloudflare-mcp',
    label: 'Cloudflare Platform',
    category: 'DevOps & Cloud',
    description: 'Manage DNS records, Cloudflare Workers, KV namespaces, and purge edge caches.',
    command: 'npx',
    args: ['-y', 'cloudflare-mcp'],
    envKeys: ['CLOUDFLARE_API_TOKEN'],
    authType: 'oauth',
    oauthProvider: 'cloudflare',
    keyGetUrl: 'https://dash.cloudflare.com/profile/api-tokens',
    keyGetLabel: 'Or Get Cloudflare Token manually',
  },
  {
    name: 'datadog-mcp-server',
    label: 'Datadog APM & Metrics',
    category: 'DevOps & Cloud',
    description: 'Query infrastructure monitors, synthetic test checks, APM traces, and host metrics.',
    command: 'npx',
    args: ['-y', 'datadog-mcp-server'],
    envKeys: ['DD_API_KEY', 'DD_APP_KEY'],
    authType: 'oauth',
    oauthProvider: 'datadog',
    keyGetUrl: 'https://app.datadoghq.com/organization-settings/api-keys',
    keyGetLabel: 'Or Get Datadog Keys manually',
  },

  // ── 5. COMMUNICATION & SUPPORT ───────────────────────────────────────────
  {
    name: 'slack-mcp',
    label: 'Slack Workspace',
    category: 'Communication & Support',
    description: 'Post channel notifications, read threads, broadcast incident reports, and DM team members.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-slack'],
    envKeys: ['SLACK_BOT_TOKEN'],
    authType: 'oauth',
    oauthProvider: 'slack',
    keyGetUrl: 'https://api.slack.com/apps',
    keyGetLabel: 'Or Get Slack Bot Token (api.slack.com)',
  },
  {
    name: 'discord-mcp',
    label: 'Discord Server',
    category: 'Communication & Support',
    description: 'Send messages, listen to server channels, and manage moderation webhooks.',
    command: 'npx',
    args: ['-y', 'discord-mcp'],
    envKeys: ['DISCORD_BOT_TOKEN'],
    authType: 'oauth',
    oauthProvider: 'discord',
    keyGetUrl: 'https://discord.com/developers/applications',
    keyGetLabel: 'Or Get Discord Token manually',
  },
  {
    name: 'zendesk-mcp-server',
    label: 'Zendesk Support',
    category: 'Communication & Support',
    description: 'Query customer support tickets, manage ticket statuses, assign agents, and search macros.',
    command: 'npx',
    args: ['-y', 'zendesk-mcp-server'],
    envKeys: ['ZENDESK_SUBDOMAIN', 'ZENDESK_API_TOKEN'],
    authType: 'oauth',
    oauthProvider: 'zendesk',
    keyGetUrl: 'https://support.zendesk.com/hc/en-us/articles/4408889105434',
    keyGetLabel: 'Or Get Zendesk API Token manually',
  },
  {
    name: 'intercom-mcp-server',
    label: 'Intercom Customer Chat',
    category: 'Communication & Support',
    description: 'Retrieve user conversations, manage active support leads, and automate reply flows.',
    url: 'https://mcp.intercom.com/mcp',
    envKeys: [],
    authType: 'oauth',
    oauthProvider: 'intercom',
  },
  {
    name: 'twilio-mcp-server',
    label: 'Twilio SMS & Voice',
    category: 'Communication & Support',
    description: 'Dispatch high-priority SMS alerts, OTP verification codes, and trigger voice incident alerts.',
    command: 'npx',
    args: ['-y', 'twilio-mcp-server'],
    envKeys: ['TWILIO_ACCOUNT_SID', 'TWILIO_AUTH_TOKEN'],
    authType: 'api_key',
    keyGetUrl: 'https://console.twilio.com',
    keyGetLabel: 'Get Twilio Keys',
  },

  // ── 6. PRODUCTIVITY & OFFICE ─────────────────────────────────────────────
  {
    name: 'google-drive-mcp',
    label: 'Google Drive & Docs',
    category: 'Productivity & Office',
    description: 'Search Google Drive, read Docs and Sheets, and organize company folders.',
    command: 'npx',
    args: ['-y', 'google-drive-mcp'],
    envKeys: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
    authType: 'oauth',
    oauthProvider: 'google',
    keyGetUrl: 'https://console.cloud.google.com/apis/credentials',
    keyGetLabel: 'Or Configure Google Cloud Credentials',
  },
  {
    name: 'notion-mcp-server',
    label: 'Notion Workspace',
    category: 'Productivity & Office',
    description: 'Read and update Notion databases, product wikis, sprint backlogs, and team documentation.',
    command: 'npx',
    args: ['-y', 'notion-mcp-server'],
    envKeys: ['NOTION_API_KEY'],
    authType: 'oauth',
    oauthProvider: 'notion',
    keyGetUrl: 'https://www.notion.so/my-integrations',
    keyGetLabel: 'Or Create Notion Token (notion.so)',
  },
  {
    name: 'linear-mcp-server',
    label: 'Linear Issues & Roadmap',
    category: 'Productivity & Office',
    description: 'Create and triage Linear issues, manage sprint cycles, and track project milestones.',
    command: 'npx',
    args: ['-y', 'linear-mcp-server'],
    envKeys: ['LINEAR_API_KEY'],
    authType: 'oauth',
    oauthProvider: 'linear',
    keyGetUrl: 'https://linear.app/settings/api',
    keyGetLabel: 'Or Generate Linear Key (linear.app)',
  },
  {
    name: 'jira-mcp-server',
    label: 'Atlassian Jira',
    category: 'Productivity & Office',
    description: 'Query enterprise Jira boards, update epics, log work, and manage sprint transitions.',
    command: 'npx',
    args: ['-y', 'jira-mcp-server'],
    envKeys: ['JIRA_HOST', 'JIRA_API_TOKEN'],
    authType: 'oauth',
    oauthProvider: 'jira',
    keyGetUrl: 'https://id.atlassian.com/manage-profile/security/api-tokens',
    keyGetLabel: 'Or Generate Jira Token (atlassian.com)',
  },
  {
    name: 'figma-mcp-server',
    label: 'Figma Design Inspector',
    category: 'Productivity & Office',
    description: 'Read component variants, inspect design tokens, styles, and extract exported SVG/PNG assets.',
    command: 'npx',
    args: ['-y', 'figma-mcp-server'],
    envKeys: ['FIGMA_ACCESS_TOKEN'],
    authType: 'oauth',
    oauthProvider: 'figma',
    keyGetUrl: 'https://www.figma.com/settings',
    keyGetLabel: 'Or Get Figma Token manually',
  },

  // ── 7. CRM, SALES & FINANCE ──────────────────────────────────────────────
  {
    name: 'stripe-mcp-server',
    label: 'Stripe Payments & Billing',
    category: 'CRM, Sales & Finance',
    description: 'Inspect invoices, customer subscriptions, dispute statuses, and webhook transaction failures.',
    command: 'npx',
    args: ['-y', 'stripe-mcp-server'],
    envKeys: ['STRIPE_SECRET_KEY'],
    authType: 'oauth',
    oauthProvider: 'stripe',
    keyGetUrl: 'https://dashboard.stripe.com/apikeys',
    keyGetLabel: 'Or Get Stripe Secret Key manually',
  },
  {
    name: 'hubspot-mcp-server',
    label: 'HubSpot CRM',
    category: 'CRM, Sales & Finance',
    description: 'Sync customer contacts, company deals, inbound lead status, and email campaign analytics.',
    command: 'npx',
    args: ['-y', 'hubspot-mcp-server'],
    envKeys: ['HUBSPOT_ACCESS_TOKEN'],
    authType: 'oauth',
    oauthProvider: 'hubspot',
    keyGetUrl: 'https://app.hubspot.com/developer/',
    keyGetLabel: 'Or Create HubSpot App Token',
  },
  {
    name: 'salesforce-mcp-server',
    label: 'Salesforce Enterprise',
    category: 'CRM, Sales & Finance',
    description: 'Query SOQL leads, enterprise accounts, opportunities, contracts, and quotes.',
    command: 'npx',
    args: ['-y', 'salesforce-mcp-server'],
    envKeys: ['SALESFORCE_INSTANCE_URL', 'SALESFORCE_ACCESS_TOKEN'],
    authType: 'oauth',
    oauthProvider: 'salesforce',
    keyGetUrl: 'https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_tokens.htm',
    keyGetLabel: 'Or Setup Salesforce Token manually',
  },
  {
    name: 'chargebee-mcp',
    label: 'Chargebee Billing',
    category: 'CRM, Sales & Finance',
    description: 'Audit recurring subscriptions, MRR metrics, dunning retries, and customer billing profiles.',
    url: 'https://mcp.chargebee.com/mcp',
    envKeys: [],
    authType: 'oauth',
    oauthProvider: 'chargebee',
  },

  // ── 8. AI & REASONING ────────────────────────────────────────────────────
  {
    name: 'memory-mcp',
    label: 'Knowledge Memory Graph',
    category: 'AI & Reasoning',
    description: 'Persistent knowledge graph memory allowing the agent to remember facts, relations, and context across turns.',
    command: 'npx',
    args: ['-y', 'memory-mcp'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'sequential-thinking-mcp',
    label: 'Sequential Thinking Planner',
    category: 'AI & Reasoning',
    description: 'Step-by-step tree-of-thought and chain-of-thought reasoning planner for complex multi-turn logic.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sequential-thinking'],
    envKeys: [],
    authType: 'none',
  },

  // ── 9. SOCIAL & DEVELOPER PROMOTION ──────────────────────────────────────
  {
    name: 'producthunt-mcp',
    label: 'Product Hunt Launchpad',
    category: 'Social & Promotion',
    description: 'Schedule maker launches, post updates, track upvotes, and engage with the product discovery community.',
    command: 'npx',
    args: ['-y', 'producthunt-mcp'],
    envKeys: ['PRODUCTHUNT_API_TOKEN'],
    authType: 'oauth',
    oauthProvider: 'producthunt',
    keyGetUrl: 'https://api.producthunt.com/v2/oauth/applications',
    keyGetLabel: 'Or Generate Product Hunt API Token',
  },
  {
    name: 'reddit-mcp',
    label: 'Reddit Community & Subreddits',
    category: 'Social & Promotion',
    description: 'Submit posts to r/programming, r/node, monitor developer discussions, and reply with technical context.',
    command: 'npx',
    args: ['-y', 'reddit-mcp-server'],
    envKeys: ['REDDIT_CLIENT_ID', 'REDDIT_CLIENT_SECRET'],
    authType: 'oauth',
    oauthProvider: 'reddit',
    keyGetUrl: 'https://www.reddit.com/prefs/apps',
    keyGetLabel: 'Or Configure Reddit App Credentials',
  },
  {
    name: 'bluesky-mcp',
    label: 'Bluesky / AT Protocol',
    category: 'Social & Promotion',
    description: 'Decentralized social posting, rich-text facets, open-source dev updates, and thread management on AT Protocol.',
    command: 'npx',
    args: ['-y', 'bluesky-mcp-server'],
    envKeys: ['BLUESKY_HANDLE', 'BLUESKY_APP_PASSWORD'],
    authType: 'oauth',
    oauthProvider: 'bluesky',
    keyGetUrl: 'https://bsky.app/settings/app-passwords',
    keyGetLabel: 'Or Get Bluesky App Password',
  },
  {
    name: 'linkedin-mcp',
    label: 'LinkedIn Professional',
    category: 'Social & Promotion',
    description: 'Publish company announcements, technical deep-dives, developer hire broadcasts, and track impressions.',
    command: 'npx',
    args: ['-y', 'linkedin-mcp-server'],
    envKeys: ['LINKEDIN_ACCESS_TOKEN'],
    authType: 'oauth',
    oauthProvider: 'linkedin',
    keyGetUrl: 'https://www.linkedin.com/developers/apps',
    keyGetLabel: 'Or Configure LinkedIn App Token',
  },
  {
    name: 'x-twitter-mcp',
    label: 'X / Twitter Developer',
    category: 'Social & Promotion',
    description: 'Publish launch threads, quote tweets, monitor mentions, analyze reach, and post automated release notes.',
    command: 'npx',
    args: ['-y', 'twitter-mcp-server'],
    envKeys: ['TWITTER_BEARER_TOKEN'],
    authType: 'oauth',
    oauthProvider: 'twitter',
    keyGetUrl: 'https://developer.x.com/en/portal/dashboard',
    keyGetLabel: 'Or Configure X Bearer Token',
  },
  {
    name: 'youtube-mcp',
    label: 'YouTube Community & Video',
    category: 'Social & Promotion',
    description: 'Automate video metadata, publish community tab announcements, inspect video analytics, and moderate comments.',
    command: 'npx',
    args: ['-y', 'youtube-mcp-server'],
    envKeys: ['YOUTUBE_API_KEY'],
    authType: 'oauth',
    oauthProvider: 'youtube',
    keyGetUrl: 'https://console.cloud.google.com/apis/library/youtube.googleapis.com',
    keyGetLabel: 'Or Configure YouTube API Key',
  },
  {
    name: 'devto-mcp',
    label: 'DEV.to Technical Blog',
    category: 'Social & Promotion',
    description: 'Cross-post technical articles, tutorial markdown drafts, changelog announcements, and monitor reader reactions.',
    command: 'npx',
    args: ['-y', 'devto-mcp'],
    envKeys: ['DEVTO_API_KEY'],
    authType: 'api_key',
    keyGetUrl: 'https://dev.to/settings/extensions',
    keyGetLabel: 'Get DEV.to API Key',
  },
  // ── NEW: official remote MCP endpoints (verified live, HTTP 200/401) ──
  {
    name: 'deepwiki',
    label: 'DeepWiki',
    category: 'Code & Git',
    description: 'Ask questions about any public repository and get grounded answers with citations to the source.',
    url: 'https://mcp.deepwiki.com/mcp',
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'context7-remote',
    label: 'Context7 Docs',
    category: 'Code & Git',
    description: 'Fetch version-matched library documentation so generated code targets the API the agent actually needs.',
    url: 'https://mcp.context7.com/mcp',
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'vercel-remote',
    label: 'Vercel',
    category: 'DevOps & Cloud',
    description: 'Inspect deployments, build logs, and project configuration for Vercel-hosted apps.',
    url: 'https://mcp.vercel.com',
    envKeys: [],
    authType: 'oauth',
    oauthProvider: 'vercel',
  },
  {
    name: 'grafana-remote',
    label: 'Grafana Cloud',
    category: 'DevOps & Cloud',
    description: 'Query dashboards, datasources and alerting rules in Grafana, including on-prem instances.',
    url: 'https://mcp.grafana.com/mcp',
    envKeys: [],
    authType: 'oauth',
    oauthProvider: 'grafana',
  },
  {
    name: 'apollo-remote',
    label: 'Apollo GraphOS',
    category: 'DevOps & Cloud',
    description: 'Explore GraphQL schemas and run operations against Apollo Studio during debugging.',
    url: 'https://mcp.apollo.io/mcp',
    envKeys: [],
    authType: 'oauth',
    oauthProvider: 'apollo',
  },
  {
    name: 'atlassian-remote',
    label: 'Atlassian Cloud',
    category: 'Communication & Support',
    description: 'Official Atlassian Cloud endpoint for Jira and Confluence, authenticated over OAuth.',
    url: 'https://mcp.atlassian.com/v1/sse',
    envKeys: [],
    authType: 'oauth',
    oauthProvider: 'atlassian',
  },
  // ── NEW: npm-published MCP servers (package existence verified) ──
  {
    name: 'chrome-devtools-mcp',
    label: 'Chrome DevTools',
    category: 'Web & Scraping',
    description: "Drive Chrome DevTools from the agent: inspect the DOM, read console and network, and profile performance.",
    command: 'npx',
    args: ['-y', 'chrome-devtools-mcp'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'desktop-commander-mcp',
    label: 'Desktop Commander',
    category: 'Code & Git',
    description: 'Cross-platform terminal and file editing with process management for agents working in a real shell.',
    command: 'npx',
    args: ['-y', '@wonderwhy-er/desktop-commander'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'git-mcp-server',
    label: 'Git Version Control',
    category: 'Code & Git',
    description: 'Secure git operations across local repositories: log, diff, branch, commit and stash.',
    command: 'npx',
    args: ['-y', '@cyanheads/git-mcp-server'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'jetbrains-mcp-proxy',
    label: 'JetBrains IDE Bridge',
    category: 'Code & Git',
    description: 'Redirect MCP tool calls into a running JetBrains IDE so the agent edits the open project.',
    command: 'npx',
    args: ['-y', '@jetbrains/mcp-proxy'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'google-maps-mcp',
    label: 'Google Maps',
    category: 'Productivity & Office',
    description: 'Geocoding, directions, distance matrices and place search for location-aware tasks.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-google-maps'],
    envKeys: ['GOOGLE_MAPS_API_KEY'],
    authType: 'api_key',
    keyGetUrl: 'https://developers.google.com/maps/documentation/webservices/get-api-key',
    keyGetLabel: 'Get Google Maps API Key',
  },
  {
    name: 'perplexity-mcp',
    label: 'Perplexity Search',
    category: 'AI & Reasoning',
    description: 'Real-time web search and cited research answers through the Perplexity API.',
    command: 'npx',
    args: ['-y', '@perplexity-ai/mcp-server'],
    envKeys: ['PERPLEXITY_API_KEY'],
    authType: 'api_key',
    keyGetUrl: 'https://www.perplexity.ai/settings/api',
    keyGetLabel: 'Get Perplexity API Key',
  },
  {
    name: 'browserbase-mcp',
    label: 'Browserbase',
    category: 'Web & Scraping',
    description: 'Managed headless browser sessions in the cloud, with captcha handling and session persistence.',
    command: 'npx',
    args: ['-y', '@browserbasehq/mcp-server-browserbase'],
    envKeys: ['BROWSERBASE_API_KEY', 'BROWSERBASE_PROJECT_ID'],
    authType: 'api_key',
    keyGetUrl: 'https://browserbase.com/dashboard',
    keyGetLabel: 'Get Browserbase API Key',
  },
  {
    name: 'heroku-mcp',
    label: 'Heroku',
    category: 'DevOps & Cloud',
    description: 'Inspect apps, dynos, config vars and logs, and run one-off commands on Heroku.',
    command: 'npx',
    args: ['-y', '@heroku/mcp-server'],
    envKeys: ['HEROKU_API_KEY'],
    authType: 'api_key',
    keyGetUrl: 'https://dashboard.heroku.com/account',
    keyGetLabel: 'Get Heroku API Key',
  },
  {
    name: 'supabase-mcp',
    label: 'Supabase',
    category: 'Databases & Storage',
    description: 'Query Postgres, inspect schemas and manage projects for Supabase-hosted databases.',
    command: 'npx',
    args: ['-y', '@supabase/mcp-server-supabase'],
    envKeys: ['SUPABASE_ACCESS_TOKEN'],
    authType: 'api_key',
    keyGetUrl: 'https://supabase.com/dashboard/account/tokens',
    keyGetLabel: 'Get Supabase Access Token',
  },
  {
    name: 'playwright-mcp-server-alt',
    label: 'Playwright (Automation)',
    category: 'Web & Scraping',
    description: 'Browser automation variant maintained by ExecuteAutomation, useful when you want explicit page control.',
    command: 'npx',
    args: ['-y', '@executeautomation/playwright-mcp-server'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'mcp-everything',
    label: 'MCP Reference Server',
    category: 'AI & Reasoning',
    description: 'Official server exercising every MCP protocol feature — useful for testing a client end to end.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-everything'],
    envKeys: [],
    authType: 'none',
  },
  // ── NEW: PyPI-published MCP servers (run via uvx) ──
  {
    name: 'aws-api-mcp',
    label: 'AWS API',
    category: 'DevOps & Cloud',
    description: "AWS Labs' official MCP server for exploring and calling AWS APIs across services.",
    command: 'uvx',
    args: ['awslabs.aws-api-mcp-server'],
    envKeys: ['AWS_REGION', 'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY'],
    authType: 'api_key',
    keyGetLabel: 'Configure AWS credentials',
  },
  {
    name: 'duckduckgo-mcp',
    label: 'DuckDuckGo Search',
    category: 'Web & Scraping',
    description: 'Keyless web search and instant answers via DuckDuckGo — no API key required.',
    command: 'uvx',
    args: ['duckduckgo-mcp-server'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'github-local-mcp',
    label: 'GitHub (Local API)',
    category: 'Code & Git',
    description: 'Local GitHub MCP server exposing the REST API over stdio, useful alongside the remote GitHub server.',
    command: 'uvx',
    args: ['github-mcp'],
    envKeys: ['GITHUB_TOKEN'],
    authType: 'api_key',
    keyGetUrl: 'https://github.com/settings/tokens',
    keyGetLabel: 'Or Generate GITHUB_TOKEN manually',
  },
  {
    name: 'markitdown-mcp',
    label: 'MarkItDown',
    category: 'Productivity & Office',
    description: "Microsoft's MarkItDown as an MCP tool: convert PDF, DOCX, XLSX and HTML into clean markdown.",
    command: 'uvx',
    args: ['markitdown-mcp'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'bigquery-mcp',
    label: 'Google BigQuery',
    category: 'Databases & Storage',
    description: 'Run BigQuery SQL, list datasets and inspect table schemas and metadata.',
    command: 'uvx',
    args: ['mcp-server-bigquery'],
    envKeys: ['GOOGLE_APPLICATION_CREDENTIALS', 'BIGQUERY_PROJECT'],
    authType: 'api_key',
    keyGetLabel: 'Point at a Google service-account JSON key',
  },
  {
    name: 'duckdb-mcp',
    label: 'DuckDB',
    category: 'Databases & Storage',
    description: 'Query local and in-process DuckDB databases, handy for analytics over CSV and Parquet files.',
    command: 'uvx',
    args: ['mcp-server-duckdb'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'medium-mcp',
    label: 'Medium',
    category: 'Social & Promotion',
    description: 'Publish posts, manage publications and read RSS feeds through the Medium API.',
    command: 'uvx',
    args: ['mcp-server-medium'],
    envKeys: ['MEDIUM_API_TOKEN'],
    authType: 'api_key',
    keyGetUrl: 'https://medium.com/me/settings',
    keyGetLabel: 'Get Medium Integration Token',
  },
  {
    name: 'notion-mcp-local',
    label: 'Notion (Local)',
    category: 'Productivity & Office',
    description: 'Self-hosted Notion MCP server for workspace pages and databases, run locally over stdio.',
    command: 'uvx',
    args: ['mcp-server-notion'],
    envKeys: ['NOTION_API_KEY'],
    authType: 'api_key',
    keyGetUrl: 'https://www.notion.so/my-integrations',
    keyGetLabel: 'Get Notion Integration Token',
  },
  {
    name: 'obsidian-mcp',
    label: 'Obsidian',
    category: 'Productivity & Office',
    description: 'Read, search and edit notes in an Obsidian vault through the Obsidian Local REST API.',
    command: 'uvx',
    args: ['mcp-server-obsidian'],
    envKeys: ['OBSIDIAN_API_KEY'],
    authType: 'api_key',
    keyGetLabel: 'Set the Obsidian Local REST API key',
  },
  {
    name: 'openai-mcp',
    label: 'OpenAI Platform',
    category: 'AI & Reasoning',
    description: 'Manage OpenAI API keys, inspect spend and track usage against the platform.',
    command: 'uvx',
    args: ['mcp-server-openai'],
    envKeys: ['OPENAI_API_KEY'],
    authType: 'api_key',
    keyGetUrl: 'https://platform.openai.com/api-keys',
    keyGetLabel: 'Get OpenAI API Key',
  },
  {
    name: 'outlook-mcp',
    label: 'Microsoft Outlook',
    category: 'Communication & Support',
    description: 'Microsoft 365 mail and calendar with audit-preserving, shareable drafts.',
    command: 'uvx',
    args: ['mcp-server-outlook'],
    envKeys: ['MS_CLIENT_ID', 'MS_CLIENT_SECRET', 'MS_TENANT_ID'],
    authType: 'api_key',
    keyGetLabel: 'Register an Entra ID application',
  },
  {
    name: 'perplexity-mcp-local',
    label: 'Perplexity (Local)',
    category: 'AI & Reasoning',
    description: 'Self-hosted Perplexity API MCP server for cited search without the hosted endpoint.',
    command: 'uvx',
    args: ['mcp-server-perplexity'],
    envKeys: ['PERPLEXITY_API_KEY'],
    authType: 'api_key',
    keyGetUrl: 'https://www.perplexity.ai/settings/api',
    keyGetLabel: 'Get Perplexity API Key',
  },
  {
    name: 'replicate-mcp',
    label: 'Replicate',
    category: 'AI & Reasoning',
    description: 'Run and inspect open models hosted on Replicate for image, audio and video generation.',
    command: 'uvx',
    args: ['mcp-server-replicate'],
    envKeys: ['REPLICATE_API_TOKEN'],
    authType: 'api_key',
    keyGetUrl: 'https://replicate.com/account/api-tokens',
    keyGetLabel: 'Get Replicate API Token',
  },
  {
    name: 'wikipedia-mcp',
    label: 'Wikipedia',
    category: 'Web & Scraping',
    description: 'Progressive-retrieval search and article lookup on Wikipedia for background facts.',
    command: 'uvx',
    args: ['mcp-server-wikipedia'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'time-mcp',
    label: 'Time & Timezones',
    category: 'Productivity & Office',
    description: 'Current time, timezone conversion and date arithmetic so the agent stops guessing the clock.',
    command: 'uvx',
    args: ['mcp-server-time'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'blender-mcp',
    label: 'Blender',
    category: 'Productivity & Office',
    description: 'Control Blender from the agent: build scenes, script objects and render through the open Blender instance.',
    command: 'uvx',
    args: ['mcp-for-blender'],
    envKeys: [],
    authType: 'none',
  },
  {
    name: 'mcp-remote-bridge',
    label: 'Remote MCP Bridge',
    category: 'AI & Reasoning',
    description: 'Turn any remote MCP endpoint into a local stdio server, so existing agents can reach hosted servers.',
    command: 'uvx',
    args: ['mcp-remote'],
    envKeys: [],
    authType: 'none',
  },
];
